-- جدول سجل مدفوعات وتجديدات الاشتراكات
-- شغّل هذا الكود مرة واحدة داخل Supabase SQL Editor

create table if not exists public.subscription_payments (
  id bigint generated by default as identity primary key,
  worker_id bigint not null references public.workers(id) on delete cascade,
  plan text not null default 'month',
  months integer not null default 1 check (months > 0),
  amount numeric(10,2) not null default 0,
  payment_method text not null default 'cash',
  payment_status text not null default 'paid',
  note text,
  previous_subscription_end date,
  new_subscription_end date not null,
  renewed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists subscription_payments_worker_id_idx
on public.subscription_payments(worker_id);

create index if not exists subscription_payments_created_at_idx
on public.subscription_payments(created_at desc);
